python3 run_self_training.py \
    --test_split ../config/setting_5/test.list \
    --model_name_or_path [MODEL_PATH] \
    --parallelize \
    --dataset_type pt \
    --ga_dev_distribution ratio \
    --per_device_train_batch_size 4 \
    --num_training_steps 4000 \
    --eval_period 100 \
    --template_dir ../templates_test \
    --output_dir ./self_train
